#!/bin/sh
# Runs inside the builder. Expects: /src = the firmware/ directory (read-only), /out = where the image goes.
# Per-install settings (named in config.env, see that file) are always required and come from the
# environment; this script writes them into src/secrets.h in a throwaway copy of the source, so the
# source tree is never touched. No fallback: an unset value fails the build with config.env's message,
# never a silent build against placeholder (secrets.example.h) credentials.
set -eu
[ -f /src/platformio.ini ] || { echo "builder: /src is not a firmware directory" >&2; exit 1; }

# Copy the source without host build output or any secrets.h.
B="${BUILD_DIR:-/work/fw}"
mkdir -p "$B"
cd /src
tar --exclude=./.pio --exclude=./src/secrets.h -cf - . | tar -xf - -C "$B"
cd "$B"

# Escape a value for a C string literal. Newlines can't be represented, so reject them.
c_escape() {
  case "$1" in *'
'*) echo "builder: $2 must not contain a newline" >&2; exit 1;; esac
  printf '%s' "$1" | sed -e 's/\\/\\\\/g' -e 's/"/\\"/g'
}

# config.env (see that file) is the single source of truth for which vars are required; sourcing it
# here -- instead of hardcoding the list -- fails the build immediately with its message if any is
# unset, so this script and config.env can't drift apart.
# `./` matters: `.` with a bare filename (no slash) does a $PATH lookup, not a cwd-relative one, and
# $PWD is never on $PATH.
set -a
. ./config.env
set +a

case "$SHOPPING_LIST_SERVER_URL" in
  http://*) ;;
  *) echo "builder: SHOPPING_LIST_SERVER_URL must start with http:// (the device has no TLS)" >&2; exit 1;;
esac
case "$SHOPPING_LIST_SERVER_URL" in
  */) echo "builder: SHOPPING_LIST_SERVER_URL must not end with a slash" >&2; exit 1;;
esac

{
  echo '#pragma once'
  echo '// Generated by firmware/builder from the environment. Not committed.'
  printf '#define SHOPPING_LIST_WIFI_SSID "%s"\n' "$(c_escape "$SHOPPING_LIST_WIFI_SSID" SHOPPING_LIST_WIFI_SSID)"
  printf '#define SHOPPING_LIST_WIFI_PASSWORD "%s"\n' "$(c_escape "$SHOPPING_LIST_WIFI_PASSWORD" SHOPPING_LIST_WIFI_PASSWORD)"
  printf '#define SHOPPING_LIST_SERVER_URL "%s"\n' "$(c_escape "$SHOPPING_LIST_SERVER_URL" SHOPPING_LIST_SERVER_URL)"
} > src/secrets.h
echo "builder: settings taken from the environment (server $SHOPPING_LIST_SERVER_URL)" >&2

pio run "$@"

version="$(grep -o 'FW_VERSION=\\"[^\\]*' platformio.ini | head -1 | cut -d'"' -f2 | tr -d '\\')"
version="${version:-unknown}"
cp .pio/build/papermono/firmware.bin "/out/${version}.bin"
echo "builder: wrote /out/${version}.bin ($(wc -c < "/out/${version}.bin") bytes, sha256 $(sha256sum "/out/${version}.bin" | cut -d' ' -f1))"
